# Generated by Django 5.0.3 on 2024-03-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baloontype',
            name='description',
            field=models.CharField(help_text='Опишите данный тип шаров', max_length=700, null=True, verbose_name='Описание данного типа шариков'),
        ),
    ]
